version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ".env"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - .:/book-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ".env"
