apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: rails-app
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: rails-app
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      name: db
      labels:
        app: rails-app
        tier: database
    spec:
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: db
        image: postgres:9.6.2
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: env
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: env
        - name: POSTGRES_DB
          valueFrom:
              secretKeyRef:
                key: POSTGRES_DB
                name: env
        - name: PGDATA
          value: /var/lib/postgresql/data
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-pv
