apiVersion: v1
kind: Service
metadata:
  name: rails-app
spec:
  selector:
    app: rails-app
  ports:
    - port: 3001
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - args:
        - bash
        - -c
        - rails s
        name: rails-app-api
        image: rails-app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_NAME
          value: "book_api_production"
        - name: DATABASE_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: "username"
              name: "db-user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: "password"
              name: "db-user-pass"
        - name: RAILS_ENV
          valueFrom:
            secretKeyRef:
              key: RAILS_ENV
              name: app-env
        - name: POSTGRES_DB
          valueFrom:
              secretKeyRef:
                key: POSTGRES_DB
                name: postgres-db
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: RAILS_SERVE_STATIC_ASSETS
          value: "true"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
        ports:
        - containerPort: 3000
