apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      restartPolicy: Never
      containers:
      - args:
        - bash
        - -c
        - rails db:create && rails db:migrate
        name: setup
        image: rails-app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: env
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: env
        - name: RAILS_ENV
          valueFrom:
            secretKeyRef:
              key: RAILS_ENV
              name: env
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY_BASE
              name: env
        - name: POSTGRES_DB
          valueFrom:
              secretKeyRef:
                key: POSTGRES_DB
                name: env
        - name: RAILS_LOG_TO_STDOUT
          valueFrom:
              secretKeyRef:
                key: RAILS_LOG_TO_STDOUT
                name: env

