default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_DB'] %>

development:
  <<: *default
  database: book_api_development

test:
  <<: *default
  database: book_api_test

production:
  <<: *default
  database: book_api_production
